site_name: Amazon Chime Meeting Summarizer
site_description: Gen AI for Call Scheduling, Speaker Diarization, and Summarization.
copyright: Made with ❤️ by Amazon Chime Meeting Summarizer contributors.
repo_name: aws-samples/amazon-chime-sdk-meeting-summarizer
repo_url: https://github.com/aws-samples/amazon-chime-sdk-meeting-summarizer
docs_dir: "docs"

# Configuration
theme:
  name: "material"
  favicon: "static/favicon.ico"
  logo: "static/chime.png"
  font:
    text: "Segoe UI"
    code: "Roboto Mono"
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: black
      accent: indigo
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: black
      accent: indigo
  highlightjs: true
  hljs_languages:
    - yaml
    - json
    - bash
  features:
    - header.autohide
    - navigation.instant
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - content.code.annotate
    - content.tooltips
    - content.tabs.link
    - content.code.copy

# Plugins
plugins:
  - search
  - glightbox
  - minify:
      minify_html: true
  - social:
      cards: true
      cards_layout_options:
        font_family: Roboto

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/aws-samples/amazon-chime-sdk-meeting-summarizer

# Extensions
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite:
      linenums: true
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - attr_list
  - md_in_html

extra_javascript:
  - https://cdn.jsdelivr.net/npm/@glidejs/glide

nav:
  - Overview: index.md
  - Getting Started: getting-started.md
  - Usage:
      - Examples:
          - Scheduling: usage/scheduling-meetings.md
  - Prompt Engineering Examples:
          - Call Scheduling: usage/scheduling.md
          - Speaker Diarization: usage/diarization.md
          - Summarization: usage/summarization.md
          - Transcription: usage/transcription.md
  - Limitations: limitations.md
  - API Reference: "api"
