name: "Release Docs"
on:
  push:
    branches:
      - mkdocs
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: pip install mkdocs-glightbox
      - run: pip install mkdocs-minify-plugin
      - run: pip install mkdocs-material-extensions
      - run: pip install pillow cairosvg
      - run: npm install
      - run: npx typedoc --out docs/api src/index.ts
      - run: mkdocs gh-deploy --force
